[package]
name = "hello_world_vsmelov"
version = "0.1.0"
authors = ["v <vladimirfol@gmail.com>"]
edition = "2018"
description = "hello_world_vsmelov"
license = "IDONTCARE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
